version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
  backend:
    container_name: spring-backend-demo
    depends_on:
      - db
    build: ./
    ports:
      - "7000:7000"